# .pre-commit-config.yaml
repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0  # You can check for newer versions later
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
