version: '3.7'

x-common-env: &common_env
  PGHOST:     ${PGHOST}
  PGPORT:     ${PGPORT}
  PGDATABASE: ${PGDATABASE}
  PGUSER:     ${PGUSER}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  DB_SECRET_NAME: ${DB_SECRET_NAME}
  LICHESS_TOKEN: ${LICHESS_TOKEN}

services:
  # ──────────────── Postgres ────────────────
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE:-knightshift}
    ports:
      - "127.0.0.1:15432:5432"  # Exposing on the host machine
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../../schemas/init:/docker-entrypoint-initdb.d
    secrets:
      - pg_password
    networks:
      - knightshift_network

  # ──────────────── KnightShift Pipeline ────────────────
  pipeline:
    build:
      context: ../..
      dockerfile: infra/docker/app.Dockerfile
    depends_on: [db]
    environment:
      <<: *common_env
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/${PGDATABASE:-knightshift}
    volumes:
      - ../../logs:/app/logs
    command: ["bash", "scripts/run.sh"]
    secrets:
      - pg_password
    networks:
      - knightshift_network
    ports:
      - "8000:8000"  # Exposing port 8000 for Prometheus metrics

  # ──────────────── Apache Airflow ────────────────
  airflow:
    build:
      context: ../..
      dockerfile: infra/docker/airflow.Dockerfile
    restart: always
    depends_on: [db]
    environment:
      <<: *common_env
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@db:5432/${PGDATABASE:-knightshift}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: America/New_York
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ../../airflow/dags:/opt/airflow/dags
      - ../../airflow/logs:/opt/airflow/logs
      - ../../airflow/plugins:/opt/airflow/plugins
      - ../../knightshift:/app/knightshift
      - ../../config:/app/config
      - ../../infra/compose/.env:/opt/airflow/.env
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db upgrade &&
        airflow users create -u admin -p admin -f admin -l admin -r Admin -e admin@example.com || true &&
        airflow scheduler & 
        exec airflow webserver --host 0.0.0.0 --port 8080
      "
    secrets:
      - pg_password
    networks:
      - knightshift_network

  # ──────────────── Prometheus ────────────────
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus
    depends_on:
      - pipeline
    networks:
      - knightshift_network

  # ──────────────── Grafana ────────────────
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - knightshift_network

secrets:
  pg_password:
    file: pg_password.txt

volumes:
  pg_data: {}
  grafana_data: {}

networks:
  knightshift_network:
    driver: bridge
