version: "3.8"

x-common-env: &common_env
  PGHOST:     ${PGHOST}
  PGPORT:     ${PGPORT}
  PGDATABASE: ${PGDATABASE}
  PGUSER:     ${PGUSER}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  DB_SECRET_NAME: ${DB_SECRET_NAME}
  LICHESS_TOKEN: ${LICHESS_TOKEN}

services:
  db:
    image: postgres:17
    restart: "no"
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE:-knightshift}
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../../schemas/init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - knightshift_network

  pipeline:
    build:
      context: ../..
      dockerfile: infra/docker/app.Dockerfile
    depends_on:
      - db
    environment:
      <<: *common_env
      DATABASE_URL: postgresql+psycopg2://${PGUSER}:${PGPASSWORD}@db:5432/${PGDATABASE:-knightshift}
    volumes:
      - ../../logs:/app/logs
    env_file:
      - .env
    networks:
      - knightshift_network

  airflow:
    build:
      context: ../..
      dockerfile: infra/docker/airflow.Dockerfile
    restart: "no"
    depends_on:
      - db
    environment:
      <<: *common_env
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${PGUSER}:${PGPASSWORD}@db:5432/${PGDATABASE:-knightshift}
      AIRFLOW__DATABASE__EXECUTEMANY_MODE: batch
      AIRFLOW__CORE__AUTH_MANAGER: airflow.auth.managers.fab.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: America/New_York
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ../../airflow/dags:/opt/airflow/dags
      - ../../airflow/logs:/opt/airflow/logs
      - ../../airflow/plugins:/opt/airflow/plugins
      - ../../knightshift:/app/knightshift
      - ../../config:/app/config
      - ../../infra/compose/.env:/opt/airflow/.env
    ports:
      - "8080:8080"
    command: >
      bash -c '
        if [ ! -f "/opt/airflow/airflow.db-initialized" ]; then
          echo "First-time DB init...";
          airflow db init &&
          touch /opt/airflow/airflow.db-initialized
        else
          echo "Migrating existing DB...";
          airflow db upgrade
        fi &&
        airflow users create -u admin -p admin -f admin -l admin -r Admin -e admin@example.com || true &&
        airflow scheduler & 
        exec airflow webserver --host 0.0.0.0 --port 8080
      '
    env_file:
      - .env
    networks:
      - knightshift_network

volumes:
  pg_data: {}

networks:
  knightshift_network:
    driver: bridge
