-- lichess_users.sql
CREATE TABLE IF NOT EXISTS lichess_users (
    id_user VARCHAR(50) PRIMARY KEY,
    val_username VARCHAR(50),
    val_title VARCHAR(10),
    val_url TEXT,
    val_real_name TEXT,
    val_location TEXT,
    val_bio TEXT,
    val_rating_fide INTEGER,
    val_rating_uscf INTEGER,
    val_rating_bullet INTEGER,
    val_rating_blitz INTEGER,
    val_rating_classical INTEGER,
    val_rating_rapid INTEGER,
    val_rating_chess960 INTEGER,
    val_rating_ultra_bullet INTEGER,
    val_country_code VARCHAR(20),
    tm_created BIGINT,
    tm_seen BIGINT,
    n_playtime_total INTEGER,
    n_playtime_tv INTEGER,
    n_games_all INTEGER,
    n_games_rated INTEGER,
    n_games_win INTEGER,
    n_games_loss INTEGER,
    n_games_draw INTEGER,
    ind_patron BOOLEAN,
    ind_streaming BOOLEAN
);
