-- lichess_users.sql
CREATE TABLE IF NOT EXISTS lichess_users (
    id VARCHAR(50) PRIMARY KEY,
    username VARCHAR(50),
    title VARCHAR(10),
    url TEXT,
    real_name TEXT,
    location TEXT,
    bio TEXT,
    fide_rating INTEGER,
    uscf_rating INTEGER,
    bullet_rating INTEGER,
    blitz_rating INTEGER,
    classical_rating INTEGER,
    rapid_rating INTEGER,
    chess960_rating INTEGER,
    ultra_bullet_rating INTEGER,
    country_code VARCHAR(5),
    created_at BIGINT,
    seen_at BIGINT,
    playtime_total INTEGER,
    playtime_tv INTEGER,
    games_all INTEGER,
    games_rated INTEGER,
    games_win INTEGER,
    games_loss INTEGER,
    games_draw INTEGER,
    patron BOOLEAN,
    streaming BOOLEAN
);
