name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest --force-reinstall  # Force reinstall pytest

    - name: Verify pytest installation
      run: |
        pip show pytest  # Verify pytest installation

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Run tests
